# export CUDA_HOME=/usr/local/cuda-11.7
# export PATH=$CUDA_HOME/bin:$PATH

# export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH


export CUDA_HOME=$CONDA_PREFIX
export CUDACXX=$CONDA_PREFIX/bin/nvcc
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib:$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export CUDA_INCLUDE_DIRS=$CONDA_PREFIX/targets/x86_64-linux/include
